#!/usr/bin/env python3
"""Generate collection/assets/ASSET-MANIFEST.md — the itemized inventory of
every visual asset the production compositor needs, per asset_manifest.py's
layer-resolution rules. Every row is checked against the real filesystem, so
status is always accurate, never hand-maintained/stale.

Statuses: MISSING (no file), CREATED (file exists, not yet reviewed),
VALIDATED (file exists and is recorded as reviewed in
collection/assets/validated.json — a small file an art reviewer maintains by
hand; this script never marks anything VALIDATED on its own).
"""
from __future__ import annotations

import json
from pathlib import Path

from asset_manifest import LAYER_STACK, METADATA_ONLY_CATEGORIES, VERSION, candidate_paths, load_trait_catalog

ROOT = Path(__file__).resolve().parents[2]
COLLECTION = ROOT / "collection"
OUT = COLLECTION / "assets" / "ASSET-MANIFEST.md"
VALIDATED_LIST = COLLECTION / "assets" / "validated.json"


def entity_values(catalog: dict[str, dict]) -> list[str]:
    return sorted(t["id"] for t in catalog.values() if t["category"] == "entity")


def rows_for_slot(slot, catalog) -> list[dict]:
    """One row per generic path this slot resolves to, across every value of
    its category (or categories, cross-joined). Entity-qualified slots also
    get one *example* entity-specific row (not all 4, to keep the manifest
    legible) marked optional — see art_prompt-style note in the header."""
    out = []
    if not slot.categories:
        candidates = candidate_paths(slot, {})
        for p in candidates:
            out.append({"slot": slot.slot, "z": slot.z, "path": p, "required": slot.required,
                        "trait": "(universal)", "optional_variant": False})
        return out

    values_by_cat = {c: sorted(t["id"] for t in catalog.values() if t["category"] == c) for c in slot.categories}
    # cross-join (categories is length 1 or 2 in this design)
    combos: list[dict[str, str]] = [{}]
    for cat, values in values_by_cat.items():
        combos = [dict(base, **{cat: v}) for base in combos for v in values]

    example_entity = entity_values(catalog)[0] if catalog else None
    for combo in combos:
        candidates = candidate_paths(slot, combo)
        label = "+".join(combo[c] for c in slot.categories)
        for i, p in enumerate(candidates):
            is_entity_variant = slot.entity_qualified and i == 0 and len(candidates) > 1
            out.append({"slot": slot.slot, "z": slot.z, "path": p, "required": slot.required and not is_entity_variant,
                        "trait": label + (f" (example: {example_entity})" if is_entity_variant else ""),
                        "optional_variant": is_entity_variant})
    return out


def main() -> None:
    catalog = load_trait_catalog()
    validated: set[str] = set()
    if VALIDATED_LIST.is_file():
        validated = set(json.loads(VALIDATED_LIST.read_text()).get("paths", []))

    all_rows = []
    for slot in LAYER_STACK:
        all_rows.extend(rows_for_slot(slot, catalog))

    missing = created = validated_n = 0
    lines = [
        "# GHOST//ROOT — asset manifest",
        "",
        "_Generated by `collection/scripts/build_asset_manifest.py` — every row is checked "
        "against the filesystem, never hand-maintained. Re-run after adding assets._",
        "",
        "Statuses: **MISSING** (no file yet) / **CREATED** (file exists, unreviewed) / "
        "**VALIDATED** (file exists and its path is recorded in `validated.json` by an art "
        "reviewer — this script never sets that status itself).",
        "",
        "Entity-qualified slots (eyes, mantle, interface, implant_front, rear_anatomy) accept "
        "either an entity-specific override or a generic fallback — see `asset_manifest.py`'s "
        "module docstring for why. Only the generic path is required; one example "
        "entity-specific path is listed per slot so the naming convention is unambiguous, not "
        "as a claim that all 4 entity variants are needed.",
        "",
        f"`access` and `signal` are metadata-only categories: {', '.join(METADATA_ONLY_CATEGORIES)} — "
        "the art bible does not name a dedicated layer for them; see the audit report.",
        "",
        "| Z | Slot | Trait(s) | Path | Required | Status |",
        "| ---: | --- | --- | --- | :---: | --- |",
    ]
    for row in sorted(all_rows, key=lambda r: (r["z"], r["slot"], str(r["path"]))):
        p = row["path"]
        rel = p.relative_to(ROOT)
        if p.is_file():
            status = "VALIDATED" if str(rel) in validated else "CREATED"
            created += 1
            if status == "VALIDATED":
                validated_n += 1
        else:
            status = "MISSING"
            missing += 1
        req = "yes" if row["required"] else "optional"
        lines.append(f"| {row['z']:03d} | {row['slot']} | {row['trait']} | `{rel}` | {req} | {status} |")

    lines += [
        "",
        f"**Totals: {len(all_rows)} rows — {missing} MISSING, {created} CREATED, {validated_n} VALIDATED.**",
        "",
        "This manifest lists paths the compositor will *look for*, computed from `traits.yaml` "
        "and the layer rules in `asset_manifest.py` — it does not by itself prove the art bible's "
        "occlusion/socket/intersection rules are satisfied for every combination; that needs the "
        "144-portrait stress-combination pilot art-bible.md's 'Asset milestones' section calls for.",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(all_rows)} rows, {missing} missing, {created} created "
          f"({validated_n} validated)")


if __name__ == "__main__":
    main()
