#!/usr/bin/env python3
"""Generate collection/assets/ASSET-MANIFEST.md from the witness-driven inventory.

The historical 105-row generic inventory is SUPERSEDED_FOR_PRODUCTION. It
included optional/empty values, illegal cross-products, and omitted authored
scenes. This report lists exact resolver paths from
manifests/collection-required-assets.json (produced by build_batch_asset_plan.py)
and checks each path against the filesystem.

Anatomical layers require an entity-qualified asset. There is no generic
class fallback. NONE/INTACT omit paint; every other required slot must exist.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COLLECTION = ROOT / "collection"
OUT = COLLECTION / "assets" / "ASSET-MANIFEST.md"
VALIDATED_LIST = COLLECTION / "assets" / "validated.json"
FULL = COLLECTION / "manifests" / "collection-required-assets.json"
BATCH = COLLECTION / "manifests" / "test-batch-required-assets.json"


def status_for(path: Path, validated: set[str]) -> str:
    rel = str(path.relative_to(ROOT))
    if not path.is_file():
        return "MISSING"
    return "VALIDATED" if rel in validated else "CREATED"


def main() -> None:
    if not FULL.is_file():
        raise SystemExit("missing manifests/collection-required-assets.json; run build_batch_asset_plan.py")
    full = json.loads(FULL.read_text())
    batch = json.loads(BATCH.read_text()) if BATCH.is_file() else {"assets": []}
    batch_paths = {a["path"] for a in batch.get("assets", [])}
    validated: set[str] = set()
    if VALIDATED_LIST.is_file():
        validated = set(json.loads(VALIDATED_LIST.read_text()).get("paths", []))

    counts = Counter()
    lines = [
        "# GHOST//ROOT — asset manifest",
        "",
        "_Generated by `collection/scripts/build_asset_manifest.py` from the witness-driven "
        "export inventory. Re-run after adding assets or regenerating "
        "`build_batch_asset_plan.py`._",
        "",
        "The historical **105**-row generic inventory is `SUPERSEDED_FOR_PRODUCTION`.",
        "",
        "Statuses: **MISSING** (no file yet) / **CREATED** (file exists, unreviewed) / "
        "**VALIDATED** (path recorded in `validated.json` by an art reviewer — this script "
        "never sets that status itself).",
        "",
        "Entity-qualified anatomical slots have **no generic fallback**. `access` and "
        "`signal` are metadata-only. Genesis and legendary tokens use complete authored "
        "scenes rather than stacked generic architecture overlays.",
        "",
        "| Slot | Path | In 20-batch | Required | Status |",
        "| --- | --- | :---: | :---: | --- |",
    ]
    for row in full["paths"]:
        path = ROOT / row["path"]
        status = status_for(path, validated)
        counts[status] += 1
        in_batch = "yes" if row["path"] in batch_paths else ""
        lines.append(
            f"| {row['slot']} | `{row['path']}` | {in_batch} | yes | {status} |"
        )

    batch_present = sum(1 for a in batch.get("assets", []) if (ROOT / a["path"]).is_file())
    lines += [
        "",
        f"**Witness-driven collection exports: {full['count']} — "
        f"{counts['MISSING']} MISSING, {counts['CREATED']} CREATED, {counts['VALIDATED']} VALIDATED.**",
        "",
        f"**20-batch unique exports: {batch.get('unique_assets_required', len(batch.get('assets', [])))} — "
        f"{batch_present} present, "
        f"{batch.get('unique_assets_required', len(batch.get('assets', []))) - batch_present} missing.**",
        "",
        full.get("count_definition", ""),
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {full['count']} collection paths, "
        f"{counts['MISSING']} missing, {counts['CREATED']} created ({counts['VALIDATED']} validated)"
    )


if __name__ == "__main__":
    main()
