#!/usr/bin/env -S npx tsx
/**
 * Deterministically (re)generate collection/launch/economics.md for both tiers.
 * Pure arithmetic from economics.ts (integer lamports). GROSS revenue only.
 */
import { writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { publicTierScenarios, allAtEarly, allAtPublic, mixedExamples, type RevenueRow } from "./economics.js";
import { CANDY_MACHINE_SUPPLY, EARLY_LAMPORTS, PUBLIC_LAMPORTS, lamportsToSol } from "./launch_config.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = `${HERE}/../../launch/economics.md`;

const row = (r: RevenueRow) => `| ${r.label} | ${r.items} | ${r.sol} SOL |`;

function build(): string {
  const pub = publicTierScenarios();
  const early = allAtEarly();
  const sellout = allAtPublic();
  const mixes = mixedExamples();

  return `# GHOST//ROOT — Primary Revenue Economics (two-tier)

_Generated by \`build_economics_report.ts\`. All figures are **gross primary revenue**, computed in exact integer lamports. Gross revenue is **not profit**: it is stated before art, engineering, independent security review, infrastructure, operations, legal work, taxes, and any refunds. No sellout is promised or forecast._

## Inputs

| Field | Value |
| --- | --- |
| Candy Machine inventory (public items) | ${CANDY_MACHINE_SUPPLY} (IDs 0002–3333; GHOST//0001 excluded) |
| Early price | ${lamportsToSol(EARLY_LAMPORTS)} SOL (${EARLY_LAMPORTS} lamports) |
| Public price | ${lamportsToSol(PUBLIC_LAMPORTS)} SOL (${PUBLIC_LAMPORTS} lamports) |
| Per-wallet cap | 5 early + 5 public — INDEPENDENT counters (early mintLimit id 1, public id 2); 10 combined max/wallet |
| Enforcement status | PDA_VERIFIED_PROGRAM_UNTESTED; MintCounter PDA seeds source-verified, program runtime + deployment integration outstanding |
| Supply model | shared pool — groups change price/access, not total supply |

## Public tier — gross primary revenue by sold-through (@0.15 SOL)

| Scenario | Items sold | Gross revenue |
| --- | ---: | ---: |
${pub.map(row).join("\n")}

At full sellout: \`${CANDY_MACHINE_SUPPLY} × 0.15 = ${sellout.sol} SOL\` gross.

_Item counts are floored to whole NFTs (10% of ${CANDY_MACHINE_SUPPLY} = 333.2 → 333 items)._

## Early-price comparison

If every item hypothetically sold at the early price: \`${CANDY_MACHINE_SUPPLY} × 0.10 = ${early.sol} SOL\` gross. This is a comparison only; the early price is gated behind the allowlist and the early group's 5-per-wallet cap (independent of the public cap).

## Mixed sellout examples (exact arithmetic)

Each row sells \`N\` items at the early price (0.10 SOL) and the remaining \`${CANDY_MACHINE_SUPPLY} − N\` at the public price (0.15 SOL).

| Mix | Items sold | Gross revenue |
| --- | ---: | ---: |
${mixes.map(row).join("\n")}

Worked arithmetic:
${mixes.map((m) => `- \`${m.label}\` = ${m.sol} SOL`).join("\n")}

## Notes

- Buyers pay the mint price **plus** their own Metaplex Core asset creation/rent and network fees; those buyer-side costs are **not** revenue to the treasury and are excluded from the figures above.
- The treasury receives only the \`solPayment\` amount for each mint.
- Unminted IDs are never sold later through an admin path; actual issuance is reported separately from the maximum edition.
`;
}

writeFileSync(OUT, build());
console.log(`Wrote ${OUT}`);
